version: 2.1

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:12.19.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    # working_directory: ~/app
    # parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm run reinstall
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running Sample tests
          command: npm run head-test