version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: "npm run reinstall" # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          start: "npm run head-test" # start server before running tests
